name: Go

on:
  push:
  pull_request:
    branches: [ "main", "test" ]

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    container:
      image: ghcr.io/vanilla-os/pico:main

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod

    - name: Build
      run: |
        go build -o apx -ldflags="-X 'main.Version=${{ github.sha }}'"
        tar -czvf apx-amd64.tar.gz apx
        GOARCH=arm64 go build -o apx -ldflags="-X 'main.Version=${{ github.sha }}'"
        tar -czvf apx-arm64.tar.gz apx
        tar -czvf apx-man.tar.gz man/man1/apx.1

    - name: Check for missing strings
      uses: vanilla-os/missing-strings-golang-action@v0.1.0

    - uses: actions/upload-artifact@v4
      with:
        name: apx
        path: apx*.tar.gz

    - uses: softprops/action-gh-release@v2
      with:
        tag_name: "continuous"
        prerelease: true
        name: "Continuous Build"
        files: apx*.tar.gz
